### ISSUE TITLE
Migrate build-test-package GitHub Action configuration into a composite action

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKModuleTemplate#131]
Migrate the `.github/workflows/build-test-package.yml` configuration into the relatively recently added [composite GitHub Action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

A [repository has been created for this action](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction).

This will prevent the need to copy the yaml configuration to remote modules, enable remote modules to always get the latest version of the script if they use `master` of the action or used a specific tagged version.

**Comment by tbirdso** [comment]
Hi @thewtex , are we trying to support modules with extra dependencies, such as [ITKUltrasound](https://github.com/KitwareMedical/ITKUltrasound/blob/master/.github/workflows/build-test-package.yml#L5)? Or should modules with any extra dependencies be expected to continue to fork the `build-test-package.yml` configuration?

**Comment by thewtex** [comment]
@tbirdso let's start with no extra dependencies, then see if we can add extra dependency support if possible! :rocket: :moon: :stars:

**Comment by tbirdso** [comment]
Hi @thewtex , per discussion in [https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/1](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/1) my understanding is that 1) Github requires one repository per composite action and 2) a composite action runs in sequence and does not support multiple jobs. 

What are your thoughts on this path forward:
- Retain a small `build-test-package.yml` actions file in the cookiecutter template to define cxx jobs and OS matrices, call composite actions, and publish to PyPI;
- Define a separate repo / action such as `ITKRemotePythonBuildAction` to handle Python build, test, packaging.

**Comment by dzenanz** [comment]
Since we have many remote modules, maybe it makes sense to have 3 test actions (one per platform) in addition to the 1 package action which you propose. That will make maintenance easier and simpler.

**Comment by blowekamp** [comment]
There seems to be some limitations with composite actions that make me wonder if they are the best option. I have created reusable step in Azure, but not GHA. My initial thoughts would be to create reusable steps that can be better customized by the package. But there is the question of how much customization is needed with the module.

> 1) Github requires one repository per composite action

In [this ](https://docs.github.com/en/actions/using-workflows/reusing-workflows) documentation I see the following example:

```
name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
```

Isn't that multiple workflows in on repo?
